using ImportSample.VehicleTransmissions;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleTransmissions
{
    public class VehicleTransmissionManager : VehicleTransmissionManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleTransmissionManager(IVehicleTransmissionRepository vehicleTransmissionRepository)
            : base(vehicleTransmissionRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}