using ImportSample.VehicleTransmissions;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleTransmissions
{
    public class VehicleTransmission : VehicleTransmissionBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleTransmission()
        {

        }

        public VehicleTransmission(Guid id, string label, int speeds, string description, string slug, VehicleTransmissionType type, bool isVerified)
            : base(id, label, speeds, description, slug, type, isVerified)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}