using ImportSample.VehicleGalleryItems;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleGalleryItems
{
    public class VehicleGalleryItem : VehicleGalleryItemBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleGalleryItem()
        {

        }

        public VehicleGalleryItem(Guid id, int order, string assetPath, VehicleGalleryItemType type)
            : base(id, order, assetPath, type)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}