using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.Districts
{
    public class DistrictManager : DistrictManagerBase
    {
        //<suite-custom-code-autogenerated>
        public DistrictManager(IDistrictRepository districtRepository)
            : base(districtRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}