using ImportSample.ProvinceCities;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.Districts
{
    public class District : DistrictBase
    {
        //<suite-custom-code-autogenerated>
        protected District()
        {

        }

        public District(Guid id, Guid provinceCityId, string name, string slug, string description)
            : base(id, provinceCityId, name, slug, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}