using ImportSample.VehicleBrands;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleModels
{
    public class VehicleModel : VehicleModelBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleModel()
        {

        }

        public VehicleModel(Guid id, Guid vehicleBrandId, string name, string description, string slug, bool isVerified)
            : base(id, vehicleBrandId, name, description, slug, isVerified)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}