using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleModels
{
    public class VehicleModelManager : VehicleModelManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleModelManager(IVehicleModelRepository vehicleModelRepository)
            : base(vehicleModelRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}