using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleCategories
{
    public class VehicleCategory : VehicleCategoryBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleCategory()
        {

        }

        public VehicleCategory(Guid id, string name, string description, string slug, bool isVerified)
            : base(id, name, description, slug, isVerified)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}