using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleCategories
{
    public class VehicleCategoryManager : VehicleCategoryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleCategoryManager(IVehicleCategoryRepository vehicleCategoryRepository)
            : base(vehicleCategoryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}