using ImportSample.Colors;
using ImportSample.VehicleModelStyles;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleModelStyles
{
    public class VehicleModelStyleManager : VehicleModelStyleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleModelStyleManager(IVehicleModelStyleRepository vehicleModelStyleRepository,
        IRepository<Color, Guid> colorRepository)
            : base(vehicleModelStyleRepository, colorRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}