using ImportSample.VehicleModelStyles;
using ImportSample.VehicleYearModels;
using ImportSample.VehicleCategories;
using ImportSample.VehicleBodyStyles;
using ImportSample.VehicleEngines;
using ImportSample.VehicleTransmissions;
using ImportSample.VehicleDriveTrains;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleModelStyles
{
    public class VehicleModelStyle : VehicleModelStyleBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleModelStyle()
        {

        }

        public VehicleModelStyle(Guid id, Guid vehicleYearModelId, Guid? vehicleCategoryId, Guid? vehicleBodyStyleId, Guid? vehicleEngineId, Guid? vehicleTransmissionId, Guid? vehicleDriveTrainId, string name, string description, string slug, int seats, int doors, string madeIn, VehicleModelStyleStatus status, string? highlight = null, float? capacity = null, float? operatingRange = null, float? combinedKm = null, float? cityKm = null, float? highwayKm = null, string? batteryType = null, float? standardCharging = null, float? rapidCharging = null, int? safetyRate = null, string? standardFeature = null, string? technicalFeature = null)
            : base(id, vehicleYearModelId, vehicleCategoryId, vehicleBodyStyleId, vehicleEngineId, vehicleTransmissionId, vehicleDriveTrainId, name, description, slug, seats, doors, madeIn, status, highlight, capacity, operatingRange, combinedKm, cityKm, highwayKm, batteryType, standardCharging, rapidCharging, safetyRate, standardFeature, technicalFeature)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}