using ImportSample.VehicleEngines;
using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleEngines
{
    public class VehicleEngineManager : VehicleEngineManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleEngineManager(IVehicleEngineRepository vehicleEngineRepository)
            : base(vehicleEngineRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}