using ImportSample.VehicleEngines;
using ImportSample.VehicleBrands;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleEngines
{
    public class VehicleEngine : VehicleEngineBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleEngine()
        {

        }

        public VehicleEngine(Guid id, Guid? vehicleBrandId, string label, int horsePower, int torque, string slug, string description, VehicleEngineType type, bool isVerified)
            : base(id, vehicleBrandId, label, horsePower, torque, slug, description, type, isVerified)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}