using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleBrands
{
    public class VehicleBrandManager : VehicleBrandManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleBrandManager(IVehicleBrandRepository vehicleBrandRepository)
            : base(vehicleBrandRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}