using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.ProvinceCities
{
    public class ProvinceCity : ProvinceCityBase
    {
        //<suite-custom-code-autogenerated>
        protected ProvinceCity()
        {

        }

        public ProvinceCity(Guid id, string name, string slug, string description)
            : base(id, name, slug, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}