using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.ProvinceCities
{
    public class ProvinceCityManager : ProvinceCityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ProvinceCityManager(IProvinceCityRepository provinceCityRepository)
            : base(provinceCityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}