using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleBodyStyles
{
    public class VehicleBodyStyleManager : VehicleBodyStyleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleBodyStyleManager(IVehicleBodyStyleRepository vehicleBodyStyleRepository)
            : base(vehicleBodyStyleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}