using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.VehicleBodyStyles
{
    public class VehicleBodyStyle : VehicleBodyStyleBase
    {
        //<suite-custom-code-autogenerated>
        protected VehicleBodyStyle()
        {

        }

        public VehicleBodyStyle(Guid id, string enName, string name, string slug, string description, bool isVerified)
            : base(id, enName, name, slug, description, isVerified)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}