using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.ColorTranslations
{
    public class ColorTranslationManager : ColorTranslationManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ColorTranslationManager(IColorTranslationRepository colorTranslationRepository)
            : base(colorTranslationRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}