using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleYearModels
{
    public class VehicleYearModelManager : VehicleYearModelManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleYearModelManager(IVehicleYearModelRepository vehicleYearModelRepository)
            : base(vehicleYearModelRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}