using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.Colors
{
    public class ColorManager : ColorManagerBase
    {
        //<suite-custom-code-autogenerated>
        public ColorManager(IColorRepository colorRepository)
            : base(colorRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}