using ImportSample.Districts;
using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace ImportSample.Wards
{
    public class Ward : WardBase
    {
        //<suite-custom-code-autogenerated>
        protected Ward()
        {

        }

        public Ward(Guid id, Guid districtId, string name, string description, string slug)
            : base(id, districtId, name, description, slug)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}