using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.Wards
{
    public class WardManager : WardManagerBase
    {
        //<suite-custom-code-autogenerated>
        public WardManager(IWardRepository wardRepository)
            : base(wardRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}