using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace ImportSample.VehicleDriveTrains
{
    public class VehicleDriveTrainManager : VehicleDriveTrainManagerBase
    {
        //<suite-custom-code-autogenerated>
        public VehicleDriveTrainManager(IVehicleDriveTrainRepository vehicleDriveTrainRepository)
            : base(vehicleDriveTrainRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}